DROP TABLE IF EXISTS `members`;
CREATE TABLE IF NOT EXISTS `members` (
  `MembershipNumber` varchar(30) NOT NULL,
  `Name` varchar(50) NOT NULL,
  `FirstName` varchar(30) NOT NULL,
  `MiddleName` varchar(30) NOT NULL,
  `LastName` varchar(30) NOT NULL,
  `PhoneNumber` varchar(30) NOT NULL,
  `AlternativeNumber` varchar(30) NOT NULL,
  `Email` varchar(30) NOT NULL,
  `DateOfBirth` date NOT NULL,
  `Gender` varchar(30) NOT NULL,
  `Nationality` varchar(30) NOT NULL,
  `NationalIdNumber` varchar(30) NOT NULL,
  `TaxPIN` varchar(30) NOT NULL,
  `Address` text NOT NULL,
  `Photo` text NOT NULL,
  `Password` text NOT NULL,
  `SourceOfIncome` varchar(30) NOT NULL,
  `Employer` text NOT NULL,
  `JobPosition` text NOT NULL,
  `PayrollNumber` varchar(30) NOT NULL,
  `EmployerAddress` text NOT NULL,
  `EmployerTelephoneNumber` varchar(30) NOT NULL,
  `GrossMonthlyIncome` double NOT NULL,
  `DateJoined` date NOT NULL,
  `MembershipStatus` varchar(30) NOT NULL,
  `LastModifiedBy` varchar(30) NOT NULL,
  `LastModifiedAt` text NOT NULL,
  PRIMARY KEY (`MembershipNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;